name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Install Node dependencies
        run: pnpm install --frozen-lockfile
      - name: Type check
        run: pnpm check
      - name: Build frontend
        run: pnpm build
      - name: Build Rust backend
        run: cargo build --manifest-path src-tauri/Cargo.toml --release
